apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ include "chart.fullname" . }}-driver
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
  fsGroupPolicy: File
  requiresRepublish: true