name: Publish chart

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  publish-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: pip install chartpress
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.RENKU_DOCKER_USERNAME }}
          password: ${{ secrets.RENKU_DOCKER_PASSWORD }}
      - name: Publish chart
        env:
          DOCKER_USERNAME: ${{ secrets.RENKU_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.RENKU_DOCKER_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
        run: |
          git config --global user.email "renku@datascience.ch"
          git config --global user.name "Renku Bot"
          export TAG=$(echo ${GITHUB_REF} |cut -d/ -f3)
          docker buildx create --name multiarch --use
          docker buildx inspect --bootstrap
          helm dep update deploy/csi-rclone
          chartpress --tag $TAG --platform linux/amd64 --platform linux/arm64 --builder docker-buildx
          helm lint deploy/csi-rclone
          chartpress --tag $TAG --platform linux/amd64 --platform linux/arm64 --builder docker-buildx --push --publish-chart 
